project:
  type: book
  output-dir: docs

book:
  page-navigation: false
  chapters:
    - index.qmd
    - src/boxplot.qmd
    - src/word_cloud.qmd
    - src/parlamento.qmd
    - src/grafico_dispersion.qmd
    - src/gatitos_inflaccion.qmd
    - src/grafico_gannt.qmd
    - src/grafico_radar.qmd
    - src/mapas.qmd
    - src/geolocalizacion.qmd
    - src/dispersiones.qmd
    - src/otros.qmd
  navbar:
    left:
      - href: 'index.html'
        text: Notebook
      - href: 'librerias.qmd'
        text: Librerías
  sidebar:
    tools:
      - href: 'https://github.com/MarioC0093/dataviz/'
        icon: github
        text: Repositorio
      - href: 'https://www.linkedin.com/in/mario-camacho-b98462ab/'
        icon: linkedin
        text: "LinkedIn"
      - href: 'https://buymeacoffee.com/marioc0093'
        icon: rocket-takeoff
        text: "Buy me a coffee"
  page-footer:
    center: 
      - text: "License"
        href: LICENSE

lang: es

#bibliography: references.bib

categories: ["Portafolio", "Dataviz"]

description: "Un portafolio que muestra algunas de mis visualizaciones y sirve de plantilla para toda persona que necesite ideas para una representación de sus datos."

abstract: |
  Una visualización de datos correcta puede expresar de forma resumida y clara gran cantidad de información, ayudando a interpretar y asimilar la información más facilmente. 

keywords: ["portafolio", "[tu área de especialización]", "proyectos", "habilidades", "experiencia"]

format:
  html:
    #grid:
    #  sidebar-width: 300px
    #  body-width: 1400px
    #  margin-width: 300px
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 200px
    code-link: true
    toc: true
    toc-title: ""
    toc-location: right
    toc-expand: true
    number-sections: false
    css: css/styles.css
    
include-in-header:
  text: |
    <meta name="keywords" content="dataviz, visualizacion, datos, R, ejemplo, personalizado"/>
    <link rel="icon" type="image/png" href="metadata/favicon.png">

editor: visual
page-layout: full
knitr:
  opts_chunk: 
    R.options:
      #width: 50
      out-width: 80%
code-fold: true
warning: false
messmessage: false
