---
title: "Boxplot"
---

```{r, child="../librerias.qmd"}
#| include: false
```

[**Librerías específicas.**]{.underline}

```{r}
library(palmerpenguins)
```

```{r}
#| fig-align: center
# Crear el gráfico de caja
penguins |> ggplot(aes(x = species, y = body_mass_g, fill = sex)) +
  geom_boxplot(outlier.color = "yellow3", outlier.shape = 16, outlier.size = 3) +  # personalización de outliers
  scale_fill_manual(values = c("male" = "#FF6347", "female" = "#4682B4"), na.value ="white") +
  labs(
    title = "Distribución de la Masa Corporal por Especie y Sexo",
    subtitle = "Pingüinos del archipiélago Palmer",
    x = "Especie de Pingüino",
    y = "Masa Corporal (g)",
    fill = "Sexo"
  ) +
  theme_classic(base_size = 10) +  # Tema clásico con tamaño de fuente base
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5, size = 12),  # Título en negrita y centrado
    plot.subtitle = element_text(hjust = 0.5, size = 12),  # Subtítulo centrado
    axis.title = element_text(face = "bold"),  # Ejes en negrita
    legend.position = "right",
    panel.background = element_rect(fill = "lightgray")  # Fondo del panel en gris claro
  )
```

